version: "3.6"
services:
  jupyter-lab:
    build:
      context: .
      platforms:
        - "linux/amd64"
        #- "linux/arm64"
        #- linux/arm32v7"
        #- linux/arm64v8"
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
        PYTHON_VERSION: ${PYTHON_VERSION}
    image: gnzsnz/jupyter-lab:${IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${LISTEN_PORT}:8888
    # optional
    # dns: ${DNS}
    #extra_hosts:
    #  - host 10.10.0.5
    #environment:
    #    USER: ${USER}
    volumes:
      - lab_env:/home/gordon/.local
      - ${PWD}/Notebooks:/home/gordon/Notebooks

volumes:
  lab_env:
