[tox]
requires =
    tox>=4
    tox-uv
env_list = build, lint, format, bandit, py{311,312,313,314}

[codequality]
description = run unit tests
runner = uv-venv-runner
extras = dev # base install

[codequality:build]
skip_install = true # ← Don't install my package, we build it here.
deps =
    build
    twine
    check-manifest
commands =
    check-manifest
    python -m build --sdist --wheel
    twine check dist/*

[codequality:bandit]
description = run bandit security checks
extras = dev
commands = bandit -r --configfile pyproject.toml {posargs:jupyter_quant}

[codequality:lint]
description = run linters
extras = dev
commands = ruff check {posargs:jupyter_quant}

[codequality:format]
description = run formaters
extras = dev
commands = ruff format --check {posargs: jupyter_quant}
