[tox]
requires =
    tox>=4
    tox-uv
env_list = build, lint, format, bandit, py{311,312,313,314}
isolated_build = true

[testenv]
description = run unit tests
runner = uv-venv-runner
extras = dev,bayes,sk-util # base install

[testenv:build]
skip_install = true # ← Don't install my package, we build it here.
deps =
    build
    twine
    check-manifest
commands =
    check-manifest
    python -m build --sdist --wheel
    twine check dist/*.tar.gz dist/*.whl dist/wheels/*.whl

[testenv:lint]
description = run linters
skip_install = true # ← Don't install my package
deps = ruff
commands = ruff check {posargs:jupyter_quant}

[testenv:format]
description = run formaters
skip_install = true # ← Don't install my package
deps = ruff
commands = ruff format --check {posargs: jupyter_quant}
